### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Manduro** [empowerhack/hababy#14]
Hi team,

I came across this project on Twitter and thought I would spend an evening to contribute using my experience with Ionic. There's no todo list or roadmap here, so I figured I'd just fix some general issues.

If there already is a plan for this project, please share it to allow the public to contribute.

**Comment by mybits** [comment]
Hi Manduro,

Thank you for your contribution. It's much much appreciated! 
There is a plan for this project and all the tickets are shared on our trello board. Please get it touch via email hababy@empowerhack.io if you'd be interested in a further help.
